on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'

permissions:
  contents: write

jobs:
  deploy:
    name: github pages 로 배포
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: node 세팅
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: package 설치
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build

      - name: github pages에 전달
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publich_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
