on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'website/**'

permissions:
  contents: write

jobs:
  deploy:
    name: github pages 로 배포
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v3
      - name: node 세팅
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: package 설치
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn build

      - name: github pages에 전달
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: <username>
          user_email: <email>
